### PR TITLE
End Session Support and Working Example

### PR DESCRIPTION
**Pull request by wi3land**
Hi Mate, Sorry if i am overstepping here. I can keep these changes on my own fork if you don't want them.
Just thought they might be support that you or other would require.

Ignore the first commit, for adding inAppBrowser that was just me merging my branches to what you have on your side.

### CODE REVIEW

**Comment by chougaard** [comment]
No worries, it's great! It's nice that you've added a running example, but I have a few comments.

Instead of implementing your own classes you should extend the functionality from the original AppAuth-JS
You should probably extend the `RevokeTokenRequest` class [here](https://github.com/openid/AppAuth-JS/blob/master/src/revoke_token_request.ts).
That object can be used by the `BaseTokenRequestHandler` in AppAuth-JS by calling `performRevokeTokenRequest()`. That should work out of the box, but if it doesn't you might want to debug the `angularRequestor` since it's a bit quick and dirty to make it work with Angular HttpClient.

Please do say if any of this is unclear 😄

**Comment by wi3land** [comment]
Hi I did see the functionality for revokingtokens. The endsession endpoint and revokation are completely seperate endpoints hence why i didn't use it. End session redirects to a log out method in the account controller for identity server that you can then sign out users. revokation endpoint is just a place to get rid unwanted tokens. 
The angularRequestor fits its functionality for me, I am in the process of creating my own HTTP handler for the rest of my app. I need to test if the endsession endpoint also revokes tokens otherwise i will need to build an endpoint in for that as well.

**Comment by chougaard** [comment]
Ah I see.
So `EndSession` will actually open a web view (like on signin) to revoke the session? 
Makes sense.

**Comment by wi3land** [comment]
It really depends how you want to do it. It does pay to have the end session endpoint.
I saw on one of your posts you mentioned you were also using identity server.
If you are using there starter pack you will see them use a  HttpContext.SignInAsync() to sign in the user.
If you don't use the end session endpoint to HttpContext.SignOutAsync() as far as the identity server is concerned that user will still be signed in even if you revoke there tokens.

**Comment by chougaard** [comment]
All done - thanks

**Pull request merged**
